name: Build and deploy container app to Azure Web App - aa-magic-app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ailandtestnetacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_1c0e1252e2e343bb84282d79c1e06890 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_43a0523ca1684890a7f8788a4387b857 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ailandtestnetacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1c0e1252e2e343bb84282d79c1e06890 }}/telegram-mini-app-aa:${{ github.sha }}
        build-args: |
          REACT_APP_PINATA_TOKEN=${{ secrets.REACT_APP_PINATA_TOKEN }}
          REACT_APP_BACKEND_URL=${{ secrets.REACT_APP_BACKEND_URL }}
          REACT_APP_CUSTOM_RPC_URL=${{ secrets.REACT_APP_CUSTOM_RPC_URL }}
          REACT_APP_TRANSAK_API_KEY=${{ secrets.REACT_APP_TRANSAK_API_KEY }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'aa-magic-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1390ced33a1c4150bb9c522be1eccf0b }}
        images: 'ailandtestnetacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1c0e1252e2e343bb84282d79c1e06890 }}/telegram-mini-app-aa:${{ github.sha }}'
